### ISSUE TITLE
Couple Errors having to do with missing token and 

### ISSUE THREAD

**Issue by TheCakesALie** [csirtgadgets/massive-octo-spice#272] opened 2015-07-07 15:51 UTC
Hello All,

We are just spinning up a CIF v2 instance and I'm hitting a couple walls. When I execute a query as CIF (like cif -q 8.8.8.8), I get a 'missing Token (--token|-T)' error. When I took a look at cif-tokens, I went ahead and added the cif user and it has admin, read, write, plus a token. So I'm somewhat stumped there.

The second issue I'm having is a weird one. When I am on my regular user, (not the CIF user) I'm able to query some IPs as well as all URLs but, most of the time when I query an IP, I get this error "invalid request at /usr/local/bin/cif line 288." Line 288 seems to be just a generic error handler.( croak($err) if($err); )

I just pulled it down and installed version 2 on June 30th of this year.

I appreciate your help!

**Comment by jgedeon120** [comment] 2015-07-07 16:23
Can you try to run your search with the -vn flags added and provide the
output?

On Tue, Jul 7, 2015 at 11:51 AM, TheCakesALie <notifications@github.com>
wrote:

> Hello All,
>
> We are just spinning up a CIF v2 instance and I'm hitting a couple walls.
> When I execute a query as CIF (like cif -q 8.8.8.8), I get a 'missing Token
> (--token|-T)' error. When I took a look at cif-tokens, I went ahead and
> added the cif user and it has admin, read, write, plus a token. So I'm
> somewhat stumped there.
>
> The second issue I'm having is a weird one. When I am on my regular user,
> (not the CIF user) I'm able to query some IPs as well as all URLs but, most
> of the time when I query an IP, I get this error "invalid request at
> /usr/local/bin/cif line 288." Line 288 seems to be just a generic error
> handler.( croak($err) if($err); )
>
> I just pulled it down and installed version 2 on June 30th of this year.
>
> I appreciate your help!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/csirtgadgets/massive-octo-spice/issues/272>.
>



-- 
Registered Linux User # 379282

**Comment by TheCakesALie** [comment] 2015-07-07 17:28
Sure

MY_USER@CIF-2:~$ cif -q 222.186.021.202 -vn
[2015-07-07T12:28:07,339Z][INFO]: starting up client...
[2015-07-07T12:28:07,339Z][INFO]: running search...
[2015-07-07T12:28:08,110Z][INFO]: status: 422
invalid request at /usr/local/bin/cif line 288.

**Comment by jgedeon120** [comment] 2015-07-07 17:38
That is one of the same errors that I am getting also in #270.  Can you
tail the /var/log/cif-router.log after you get the error?



Wes and glovino, this may be related.

On Tue, Jul 7, 2015 at 1:28 PM, TheCakesALie <notifications@github.com>
wrote:

> Sure
>
> MY_USER@CIF-2:~$ cif -q 222.186.021.202 -vn
> [2015-07-07T12:28:07,339Z][INFO]: starting up client...
> [2015-07-07T12:28:07,339Z][INFO]: running search...
> [2015-07-07T12:28:08,110Z][INFO]: status: 422
> invalid request at /usr/local/bin/cif line 288.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/csirtgadgets/massive-octo-spice/issues/272#issuecomment-119276169>
> .
>



-- 
Registered Linux User # 379282

**Comment by TheCakesALie** [comment] 2015-07-07 17:42
Okay, sorry to duplicate the issue! Didn't see that somehow.
I tailed it and got this:
[2015-07-07T12:40:37,954Z][ERROR]: invalid key at /opt/cif/bin/../lib/perl5/CIF/Storage/ElasticSearch.pm line 393.

**Comment by jgedeon120** [comment] 2015-07-07 17:45
I'm not sure if it's a duplicate or not.  I have at least have not seen
that error in mine.  Most make it look like an Elasticsearch issue but
checking the elasticsearch directly I am not seeing the issue.


On Tue, Jul 7, 2015 at 1:42 PM, TheCakesALie <notifications@github.com>
wrote:

> Okay, sorry to duplicate the issue! Didn't see that somehow.
> I tailed it and got this:
> [2015-07-07T12:40:37,954Z][ERROR]: invalid key at
> /opt/cif/bin/../lib/perl5/CIF/Storage/ElasticSearch.pm line 393.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/csirtgadgets/massive-octo-spice/issues/272#issuecomment-119279948>
> .
>



-- 
Registered Linux User # 379282

**Comment by giovino** [comment] 2015-07-07 18:04
1) "invalid request at /usr/local/bin/cif line 288"

I was able to duplicate, logged here: https://github.com/csirtgadgets/massive-octo-spice/issues/270#issuecomment-119284169

2) cif user question

We do not drop a CIF client configuration file for the "CIF user" created during install. You can see an example of one in your users home dir:

```
$ cat /home/<username>/.cif.yml 
---
client:
  no_verify_ssl: 1
  remote: https://localhost
  token: c454...
```

You could copy that file to ```/home/cif/``` or create a new token like you did and create a similar config file in ```/home/cif/```

Thanks!

**Comment by TheCakesALie** [comment] 2015-07-07 18:14
That did the trick for my token issue giovino. Thanks!
Also, what is the default password for the CIF account?

**Comment by giovino** [comment] 2015-07-07 18:23
there is not a default password, it is set to a invalid result:

```
$ sudo less /etc/shadow | grep cif
cif:!:16623:0:99999:7:::
```

"If the password field contains some string that is not a valid result of crypt(3), for instance ! or *, the user will not be able to use a unix password to log in (but the user may log in the system by other means)."
http://linux.die.net/man/5/shadow

**Comment by TheCakesALie** [comment] 2015-07-07 18:28
Got it. Thanks again!

**Comment by wesyoung** [comment] 2015-07-08 11:46
i'm gonna mark this as a duplicate of #270 and we'll keep track of it there. if you wanna see updates @TheCakesALie subscribe to that thread, ok?

**Closed by wesyoung** 2015-07-08 11:46 UTC

**Comment by ryank01** [comment] 2018-06-29 14:07
Hello All, 
I'm trying to find `cif-router.conf` and I can't seem to locate it. Can anyone point me to where it's at ? I'm actually trying to figure out how CIF configures it's shards for the monthly indices. 
Thanks !
